services:
  tracking:
    image: jaegertracing/all-in-one:latest
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    ports:
      - "4317:4317" # OpenTelemetry gRPC receiver
      - "4318:4318" # OpenTelemetry receiver
      - "14268:14268" # Jaeger receiver
      - "16686:16686" # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  
  app:
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: "1"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CDN_BASE_URL: http://localhost:13001
      LOG_LEVEL: ${LOG_LEVEL:-info}
      OTLP_SPAN_ENDPOINT: http://tracking:4317
      OTLP_METRIC_ENDPOINT: http://tracking:4318/v1/metrics
      OTLP_SERVICE_NAME: giss
      DB_MAX_THREAD_POOL: ${DB_MAX_THREAD_POOL:-20}
    ports:
      - ${APP_PORT:-13001-13005}:3000
    depends_on:
      - tracking

  openapi-generator-cli:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi.yaml:/packages/openapi.yaml
      - ./packages/gen-server:/packages/gen-server
    command:
      - generate
      - -i
      - /packages/openapi.yaml
      - -g
      - rust-axum
      - -o
      - /packages/gen-server
      - --package-name
      - gen-server