//! Deterministic, code-generated fixture corpus shared by the criterion
//! benches (`benches/*.rs`), the integration tests (`tests/*.rs`), and the
//! `benchmark` load-test bin (`src/bin/benchmark.rs`), all of which pull
//! this file in via `#[path = "..."] mod fixtures;` rather than depending on
//! a crate, since it needs to be reachable from three different compilation
//! units (a `[[bench]]` target, `tests/`, and a `[[bin]]` target).
//!
//! Nothing here is a committed binary asset: every fixture is generated at
//! runtime from a fixed RNG seed, so output is byte-identical across runs
//! and machines. Generated bytes are cached under `target/fixtures/` (or
//! `$CARGO_TARGET_DIR/fixtures/`) so repeated `cargo bench` / `cargo test`
//! invocations don't pay the generation cost again. If the generation logic
//! below ever changes, delete that cache directory to pick up the change.
#![allow(dead_code)]

use image::{DynamicImage, ImageBuffer, ImageFormat, Rgb, RgbImage, Rgba, RgbaImage};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use std::io::Cursor;
use std::path::PathBuf;

/// Fixed seed so every fixture is byte-identical across runs and machines.
const SEED: u64 = 0x1BAD_1DEA_C0FF_EE42;

pub const PHOTO_LIKE_W: u32 = 1920;
pub const PHOTO_LIKE_H: u32 = 1080;
pub const TINY_SIZE: u32 = 64;
pub const ALPHA_SIZE: u32 = 512;
pub const BOMB_SIDE: u32 = 10_000;

fn cache_root() -> PathBuf {
    let target_dir = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| "target".to_string());
    PathBuf::from(target_dir).join("fixtures")
}

/// Read `name` from the on-disk fixture cache, generating (and caching) it
/// on first use. Falls back to plain in-memory generation if the cache
/// directory can't be created/written (e.g. a read-only checkout).
fn cached(name: &str, generate: impl FnOnce() -> Vec<u8>) -> Vec<u8> {
    let dir = cache_root();
    let path = dir.join(name);

    if let Ok(bytes) = std::fs::read(&path) {
        return bytes;
    }

    let bytes = generate();

    if std::fs::create_dir_all(&dir).is_ok() {
        let _ = std::fs::write(&path, &bytes);
    }

    bytes
}

fn encode(img: &DynamicImage, format: ImageFormat) -> Vec<u8> {
    let mut buf = Cursor::new(Vec::new());
    img.write_to(&mut buf, format)
        .expect("fixture encoding should never fail");
    buf.into_inner()
}

/// PNG-encode at `Best`/`Up` instead of `write_to`'s `Fast`/`Adaptive`
/// default. Used for `bomb()`: a solid colour compresses dramatically
/// better under `Best` (single-digit KB instead of low-single-digit MB at
/// 10000x10000), which is the whole point of that fixture.
fn encode_png_best_compression(img: &RgbImage) -> Vec<u8> {
    use image::ExtendedColorType;
    use image::codecs::png::{CompressionType, FilterType as PngFilterType, PngEncoder};
    use image::ImageEncoder;

    let mut buf = Cursor::new(Vec::new());
    PngEncoder::new_with_quality(&mut buf, CompressionType::Best, PngFilterType::Up)
        .write_image(img.as_raw(), img.width(), img.height(), ExtendedColorType::Rgb8)
        .expect("fixture PNG encoding should never fail");
    buf.into_inner()
}

fn rng_for(label: &str) -> StdRng {
    // Mix the label into the seed so different fixtures don't share an
    // identical pixel stream, while staying fully deterministic per label.
    let mut mix = SEED;
    for byte in label.bytes() {
        mix = mix.rotate_left(5) ^ byte as u64;
    }
    StdRng::seed_from_u64(mix)
}

/// Smooth gradient + per-pixel noise: compresses like a real photo, not a
/// flat colour.
pub fn gradient_noise_rgb(width: u32, height: u32) -> RgbImage {
    let mut rng = rng_for(&format!("gradient_noise_{width}x{height}"));
    ImageBuffer::from_fn(width, height, |x, y| {
        let gx = (x as f32 / width.max(1) as f32 * 255.0) as i32;
        let gy = (y as f32 / height.max(1) as f32 * 255.0) as i32;
        let noise: i32 = rng.gen_range(-24..=24);
        let clamp = |v: i32| v.clamp(0, 255) as u8;
        Rgb([
            clamp(gx + noise),
            clamp(gy + noise),
            clamp((gx + gy) / 2 + noise),
        ])
    })
}

/// A single solid colour. Compresses to almost nothing via DEFLATE.
pub fn solid_rgb(width: u32, height: u32) -> RgbImage {
    ImageBuffer::from_pixel(width, height, Rgb([36, 140, 210]))
}

/// RGBA image with a transparent border whose RGB channels are garbage
/// (non-zero). This is the PNG -> JPEG fringing case: flattening onto a
/// background without properly handling alpha bleeds the garbage colour
/// into the visible border.
pub fn alpha_fringe_rgba(size: u32) -> RgbaImage {
    let mut rng = rng_for(&format!("alpha_fringe_{size}"));
    let border = (size / 16).max(4);
    ImageBuffer::from_fn(size, size, |x, y| {
        let on_border = x < border || y < border || x >= size - border || y >= size - border;
        if on_border {
            // Fully transparent, but with non-zero "garbage" RGB underneath.
            // `gen` is a reserved keyword under the 2024 edition; rand 0.8's
            // `Rng::gen` needs the raw-identifier escape here.
            Rgba([rng.r#gen(), rng.r#gen(), rng.r#gen(), 0])
        } else {
            let gx = (x as f32 / size as f32 * 255.0) as u8;
            let gy = (y as f32 / size as f32 * 255.0) as u8;
            Rgba([gx, gy, 200, 255])
        }
    })
}

/// 1920x1080 photo-like JPEG.
pub fn photo_like() -> Vec<u8> {
    cached("photo_like.jpg", || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(PHOTO_LIKE_W, PHOTO_LIKE_H));
        encode(&img, ImageFormat::Jpeg)
    })
}

/// 1920x1080 solid-colour PNG - compresses to almost nothing.
pub fn flat() -> Vec<u8> {
    cached("flat.png", || {
        let img = DynamicImage::ImageRgb8(solid_rgb(PHOTO_LIKE_W, PHOTO_LIKE_H));
        encode(&img, ImageFormat::Png)
    })
}

/// 512x512 RGBA PNG with a transparent border and garbage RGB underneath it.
pub fn alpha() -> Vec<u8> {
    cached("alpha.png", || {
        let img = DynamicImage::ImageRgba8(alpha_fringe_rgba(ALPHA_SIZE));
        encode(&img, ImageFormat::Png)
    })
}

/// 64x64 photo-like JPEG - small enough to exercise upscaling.
pub fn tiny() -> Vec<u8> {
    cached("tiny.jpg", || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(TINY_SIZE, TINY_SIZE));
        encode(&img, ImageFormat::Jpeg)
    })
}

/// A PNG that is tiny on disk but decodes to 10000x10000 (solid colour, so
/// DEFLATE crushes it). Used by decompression-bomb / resource-limit tests.
pub fn bomb() -> Vec<u8> {
    cached("bomb.png", || {
        let img = solid_rgb(BOMB_SIDE, BOMB_SIDE);
        encode_png_best_compression(&img)
    })
}

/// Same photo-like content, at an arbitrary size/format - used by the decode
/// benchmark to cover multiple resolutions per codec without hand-generating
/// each one.
pub fn photo_like_sized(width: u32, height: u32, format: ImageFormat) -> Vec<u8> {
    let ext = match format {
        ImageFormat::Jpeg => "jpg",
        ImageFormat::Png => "png",
        ImageFormat::WebP => "webp",
        _ => "bin",
    };
    cached(&format!("photo_like_{width}x{height}.{ext}"), || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(width, height));
        encode(&img, format)
    })
}

/// content-type for a fixture identified by name, as served by the
/// `benchmark` bin's local origin server and used to pick a decode/encode
/// extension in tests.
pub fn content_type_for(name: &str) -> &'static str {
    match name {
        "photo_like" | "tiny" => "image/jpeg",
        "flat" | "alpha" | "bomb" => "image/png",
        _ => "application/octet-stream",
    }
}

/// Look up one of the named fixtures by string name (used by the local
/// fixture HTTP server in `src/bin/benchmark.rs`, where the set to serve is
/// configured via an env var).
pub fn by_name(name: &str) -> Option<Vec<u8>> {
    match name {
        "photo_like" => Some(photo_like()),
        "flat" => Some(flat()),
        "alpha" => Some(alpha()),
        "tiny" => Some(tiny()),
        "bomb" => Some(bomb()),
        _ => None,
    }
}
