//! Deterministic, code-generated fixture corpus shared by the criterion
//! benches (`benches/*.rs`), the integration tests (`tests/*.rs`), and the
//! `benchmark` load-test bin (`src/bin/benchmark.rs`), all of which pull
//! this file in via `#[path = "..."] mod fixtures;` rather than depending on
//! a crate, since it needs to be reachable from three different compilation
//! units (a `[[bench]]` target, `tests/`, and a `[[bin]]` target).
//!
//! Nothing here is a committed binary asset: every fixture is generated at
//! runtime from a fixed RNG seed, so output is byte-identical across runs
//! and machines. Generated bytes are cached under `target/fixtures/` (or
//! `$CARGO_TARGET_DIR/fixtures/`) so repeated `cargo bench` / `cargo test`
//! invocations don't pay the generation cost again. If the generation logic
//! below ever changes, delete that cache directory to pick up the change.
#![allow(dead_code)]

use image::{DynamicImage, ImageBuffer, ImageFormat, Rgb, RgbImage, Rgba, RgbaImage};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use std::io::Cursor;
use std::path::PathBuf;

/// Fixed seed so every fixture is byte-identical across runs and machines.
const SEED: u64 = 0x1BAD_1DEA_C0FF_EE42;

pub const PHOTO_LIKE_W: u32 = 1920;
pub const PHOTO_LIKE_H: u32 = 1080;
pub const TINY_SIZE: u32 = 64;
pub const ALPHA_SIZE: u32 = 512;
pub const BOMB_SIDE: u32 = 10_000;

fn cache_root() -> PathBuf {
    let target_dir = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| "target".to_string());
    PathBuf::from(target_dir).join("fixtures")
}

/// Read `name` from the on-disk fixture cache, generating (and caching) it
/// on first use. Falls back to plain in-memory generation if the cache
/// directory can't be created/written (e.g. a read-only checkout).
fn cached(name: &str, generate: impl FnOnce() -> Vec<u8>) -> Vec<u8> {
    let dir = cache_root();
    let path = dir.join(name);

    if let Ok(bytes) = std::fs::read(&path) {
        return bytes;
    }

    let bytes = generate();

    if std::fs::create_dir_all(&dir).is_ok() {
        let _ = std::fs::write(&path, &bytes);
    }

    bytes
}

fn encode(img: &DynamicImage, format: ImageFormat) -> Vec<u8> {
    let mut buf = Cursor::new(Vec::new());
    img.write_to(&mut buf, format)
        .expect("fixture encoding should never fail");
    buf.into_inner()
}

/// PNG-encode at `Best`/`Up` instead of `write_to`'s `Fast`/`Adaptive`
/// default. Used for `bomb()`: a solid colour compresses dramatically
/// better under `Best` (single-digit KB instead of low-single-digit MB at
/// 10000x10000), which is the whole point of that fixture.
fn encode_png_best_compression(img: &RgbImage) -> Vec<u8> {
    use image::ExtendedColorType;
    use image::ImageEncoder;
    use image::codecs::png::{CompressionType, FilterType as PngFilterType, PngEncoder};

    let mut buf = Cursor::new(Vec::new());
    PngEncoder::new_with_quality(&mut buf, CompressionType::Best, PngFilterType::Up)
        .write_image(
            img.as_raw(),
            img.width(),
            img.height(),
            ExtendedColorType::Rgb8,
        )
        .expect("fixture PNG encoding should never fail");
    buf.into_inner()
}

fn rng_for(label: &str) -> StdRng {
    // Mix the label into the seed so different fixtures don't share an
    // identical pixel stream, while staying fully deterministic per label.
    let mut mix = SEED;
    for byte in label.bytes() {
        mix = mix.rotate_left(5) ^ byte as u64;
    }
    StdRng::seed_from_u64(mix)
}

/// Smooth gradient + per-pixel noise: compresses like a real photo, not a
/// flat colour.
pub fn gradient_noise_rgb(width: u32, height: u32) -> RgbImage {
    let mut rng = rng_for(&format!("gradient_noise_{width}x{height}"));
    ImageBuffer::from_fn(width, height, |x, y| {
        let gx = (x as f32 / width.max(1) as f32 * 255.0) as i32;
        let gy = (y as f32 / height.max(1) as f32 * 255.0) as i32;
        let noise: i32 = rng.gen_range(-24..=24);
        let clamp = |v: i32| v.clamp(0, 255) as u8;
        Rgb([
            clamp(gx + noise),
            clamp(gy + noise),
            clamp((gx + gy) / 2 + noise),
        ])
    })
}

/// A single solid colour. Compresses to almost nothing via DEFLATE.
pub fn solid_rgb(width: u32, height: u32) -> RgbImage {
    ImageBuffer::from_pixel(width, height, Rgb([36, 140, 210]))
}

/// RGBA image with a transparent border whose RGB channels are garbage
/// (non-zero). This is the PNG -> JPEG fringing case: flattening onto a
/// background without properly handling alpha bleeds the garbage colour
/// into the visible border.
pub fn alpha_fringe_rgba(size: u32) -> RgbaImage {
    let mut rng = rng_for(&format!("alpha_fringe_{size}"));
    let border = (size / 16).max(4);
    ImageBuffer::from_fn(size, size, |x, y| {
        let on_border = x < border || y < border || x >= size - border || y >= size - border;
        if on_border {
            // Fully transparent, but with non-zero "garbage" RGB underneath.
            // `gen` is a reserved keyword under the 2024 edition; rand 0.8's
            // `Rng::gen` needs the raw-identifier escape here.
            Rgba([rng.r#gen(), rng.r#gen(), rng.r#gen(), 0])
        } else {
            let gx = (x as f32 / size as f32 * 255.0) as u8;
            let gy = (y as f32 / size as f32 * 255.0) as u8;
            Rgba([gx, gy, 200, 255])
        }
    })
}

/// 1920x1080 photo-like JPEG.
pub fn photo_like() -> Vec<u8> {
    cached("photo_like.jpg", || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(PHOTO_LIKE_W, PHOTO_LIKE_H));
        encode(&img, ImageFormat::Jpeg)
    })
}

/// 1920x1080 solid-colour PNG - compresses to almost nothing.
pub fn flat() -> Vec<u8> {
    cached("flat.png", || {
        let img = DynamicImage::ImageRgb8(solid_rgb(PHOTO_LIKE_W, PHOTO_LIKE_H));
        encode(&img, ImageFormat::Png)
    })
}

/// 512x512 RGBA PNG with a transparent border and garbage RGB underneath it.
pub fn alpha() -> Vec<u8> {
    cached("alpha.png", || {
        let img = DynamicImage::ImageRgba8(alpha_fringe_rgba(ALPHA_SIZE));
        encode(&img, ImageFormat::Png)
    })
}

/// 64x64 photo-like JPEG - small enough to exercise upscaling.
pub fn tiny() -> Vec<u8> {
    cached("tiny.jpg", || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(TINY_SIZE, TINY_SIZE));
        encode(&img, ImageFormat::Jpeg)
    })
}

/// A PNG that is tiny on disk but decodes to 10000x10000 (solid colour, so
/// DEFLATE crushes it). Used by decompression-bomb / resource-limit tests.
pub fn bomb() -> Vec<u8> {
    cached("bomb.png", || {
        let img = solid_rgb(BOMB_SIDE, BOMB_SIDE);
        encode_png_best_compression(&img)
    })
}

/// #50: source dimensions for [`gravity_marker`] - landscape (2:1), so
/// `ResizeType::Fill` into a square or narrower box always has real overflow
/// to crop on at least one axis, which is what makes the gravity/crop
/// golden-image tests meaningful in the first place (a centred crop and a
/// directional crop of a *square* source into a square box could
/// legitimately produce the same pixels).
pub const MARKER_W: u32 = 400;
pub const MARKER_H: u32 = 200;
/// Marker square side length, in source pixels. Small relative to
/// `MARKER_W`/`MARKER_H` so a half-size crop window
/// (`MARKER_W / 2 x MARKER_H / 2`, the size the gravity tests below crop to)
/// still isolates a single corner marker with margin either side, and small
/// enough relative to a 2x integer downscale (the gravity/crop tests' `Fill`
/// case) that interior marker pixels survive resampling as the exact
/// marker colour - see `gravity_marker`'s own doc comment.
pub const MARKER_SIZE: u32 = 40;

/// One value per corner plus the centre, each visually distinct (pure
/// primary/secondary colours) so a decoded output pixel can be matched back
/// to exactly one marker with a simple equality check - no thresholding or
/// distance metric needed.
pub const MARKER_NORTHWEST: Rgb<u8> = Rgb([220, 20, 20]); // red
pub const MARKER_NORTHEAST: Rgb<u8> = Rgb([20, 180, 20]); // green
pub const MARKER_SOUTHWEST: Rgb<u8> = Rgb([20, 20, 220]); // blue
pub const MARKER_SOUTHEAST: Rgb<u8> = Rgb([220, 200, 20]); // yellow
pub const MARKER_CENTER: Rgb<u8> = Rgb([200, 20, 200]); // magenta
pub const MARKER_BACKGROUND: Rgb<u8> = Rgb([110, 110, 110]); // neutral grey

/// `MARKER_W x MARKER_H` solid grey field with five `MARKER_SIZE`-square,
/// solid-colour markers stamped at each corner and the centre (#50) - the
/// "distinctive marker in the fixture" the gravity/crop golden-image tests
/// (`src/services/image/handler.rs::tests`) assert the position of, instead
/// of only checking output dimensions (which a centred crop and e.g. a
/// north crop of the same source share, even though their *content*
/// differs).
///
/// Every region (background and every marker) is a single flat colour, not
/// noise or a gradient - deliberately, so that after a resize/crop pass
/// (including `Fill`'s cover-scale-then-crop, which does real resampling,
/// not just pixel extraction) a pixel sampled from *inside* a marker
/// square, away from its edge, still decodes to exactly that marker's RGB:
/// every sample point a resampling kernel could touch within one marker's
/// interior is that same flat colour, so there's nothing to blend away from.
pub fn gravity_marker_rgb(width: u32, height: u32) -> RgbImage {
    let marker = MARKER_SIZE.min(width / 4).min(height / 4).max(1);
    let cx = width / 2 - marker / 2;
    let cy = height / 2 - marker / 2;

    ImageBuffer::from_fn(width, height, |x, y| {
        let in_square = |sx: u32, sy: u32| x >= sx && x < sx + marker && y >= sy && y < sy + marker;
        if in_square(0, 0) {
            MARKER_NORTHWEST
        } else if in_square(width - marker, 0) {
            MARKER_NORTHEAST
        } else if in_square(0, height - marker) {
            MARKER_SOUTHWEST
        } else if in_square(width - marker, height - marker) {
            MARKER_SOUTHEAST
        } else if in_square(cx, cy) {
            MARKER_CENTER
        } else {
            MARKER_BACKGROUND
        }
    })
}

/// PNG encoding of [`gravity_marker_rgb`] at `MARKER_W x MARKER_H`.
pub fn gravity_marker() -> Vec<u8> {
    cached("gravity_marker.png", || {
        let img = DynamicImage::ImageRgb8(gravity_marker_rgb(MARKER_W, MARKER_H));
        encode(&img, ImageFormat::Png)
    })
}

/// Same photo-like content, at an arbitrary size/format - used by the decode
/// benchmark to cover multiple resolutions per codec without hand-generating
/// each one.
pub fn photo_like_sized(width: u32, height: u32, format: ImageFormat) -> Vec<u8> {
    let ext = match format {
        ImageFormat::Jpeg => "jpg",
        ImageFormat::Png => "png",
        ImageFormat::WebP => "webp",
        _ => "bin",
    };
    cached(&format!("photo_like_{width}x{height}.{ext}"), || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(width, height));
        encode(&img, format)
    })
}

/// Same photo-like content, at an arbitrary size, AVIF-encoded via the
/// caller-supplied `encode_fn` (#67/#68) - deliberately *not* calling
/// `avif_codec::encode` directly here (unlike `photo_like_sized`'s
/// `image::write_to` call above): this module is `#[path]`-included from
/// three different compilation contexts (`handler.rs`'s own test module,
/// inside the `emgr` lib crate itself; `benches/*.rs` and `tests/*.rs`,
/// separate crates that depend on `emgr` externally), and those two
/// contexts need opposite spellings (`crate::services::...` inside the
/// lib, `emgr::services::...` outside it) to name the same function -
/// there is no single path that resolves in both. Accepting the encoder
/// as a parameter sidesteps that entirely: each caller passes whichever
/// spelling is correct for its own compilation context.
pub fn photo_like_sized_avif(
    width: u32,
    height: u32,
    encode_fn: impl FnOnce(&DynamicImage) -> Vec<u8>,
) -> Vec<u8> {
    cached(&format!("photo_like_{width}x{height}.avif"), || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(width, height));
        encode_fn(&img)
    })
}

// ---------------------------------------------------------------------
// Real-photo fixtures
//
// `gradient_noise_rgb` above (smooth gradient + i.i.d. per-pixel noise) is
// close to incompressible high-frequency noise, which `adr/0003-webp-
// measurement.md` and `adr/0004-avif-measurement.md` both found gives
// codec comparisons the wrong answer - sometimes inverted (WebP decode
// measured *slower* than the pure-Rust decoder it replaced on this
// synthetic fixture; ~2.24x *faster* on real photos), sometimes wildly
// off-scale (AVIF decode ~30x slower on synthetic noise than on real
// photos, because there's far more compressed residual to walk through).
// These two embedded photographs give the decode/encode/pipeline benches
// a real photographic-content axis to measure alongside the synthetic
// one, instead of only ever seeing noise.
//
// Both are NASA public-domain photographs (17 U.S.C. §105 - a work of the
// U.S. federal government), re-encoded and downscaled from their
// Wikimedia Commons originals; see `benches/fixtures/real/ATTRIBUTION.md`
// for the exact source URLs, licence confirmation, and processing steps.
// Deliberately not the Kodak True Color corpus those two ADRs used for
// their own scratch-crate measurements - Kodak's redistribution licence
// isn't established as permissive enough to commit into this repository.
//
// Embedded via `include_bytes!` (not read from disk at bench time): this
// file is pulled into three different compilation units via `#[path]`
// (see the module doc comment at the top of this file), each with a
// different process working directory, so a runtime `std::fs::read`
// relative path would be fragile in a way a compile-time include isn't.
// `include_bytes!`'s path is resolved relative to this physical source
// file's own directory (`benches/`), regardless of which crate includes
// it.
const REAL_PHOTO_PRIMARY_BYTES: &[u8] = include_bytes!("fixtures/real/blue-marble.jpg");
const REAL_PHOTO_SECONDARY_BYTES: &[u8] = include_bytes!("fixtures/real/earthrise.jpg");

/// Decode one of the embedded real-photo sources. Not cached on disk like
/// the generated fixtures below - decoding a ~300KB/~80KB JPEG once per
/// process is cheap enough not to need it, and the *output* of
/// `real_photo_sized`/`real_photo_sized_avif` (which do get disk-cached)
/// is what repeated `cargo bench` runs actually reuse.
fn real_photo_base(bytes: &'static [u8]) -> DynamicImage {
    image::load_from_memory_with_format(bytes, ImageFormat::Jpeg)
        .expect("embedded real-photo fixture should always decode")
}

/// Scale `base` to cover a `width x height` box (matching the longer of
/// the two scale factors, like `ResizeType::Fill`'s cover-then-crop in
/// `src/services/image/handler.rs`), then centre-crop to exactly that box.
/// Never upscales past what `base`'s own resolution supports for the sizes
/// this file actually requests (checked in `real_photo_sized`'s doc
/// comment) - deliberately not calling into `handler.rs` itself here, so
/// this fixture-generation code can't accidentally depend on the same
/// logic the benches go on to measure.
fn cover_resize(base: &DynamicImage, width: u32, height: u32) -> RgbImage {
    let (bw, bh) = (base.width() as f64, base.height() as f64);
    let scale = (width as f64 / bw).max(height as f64 / bh);
    let rw = (bw * scale).ceil().max(width as f64) as u32;
    let rh = (bh * scale).ceil().max(height as f64) as u32;
    let resized = base.resize_exact(rw, rh, image::imageops::FilterType::Lanczos3);
    let x = (resized.width() - width) / 2;
    let y = (resized.height() - height) / 2;
    resized.crop_imm(x, y, width, height).into_rgb8()
}

/// Real-photo content (the primary source, `blue-marble.jpg`) at an
/// arbitrary size/format - the real-photo counterpart to
/// `photo_like_sized` above, same signature, same disk-cache scheme. Every
/// size this benchmark suite requests (max 1920x1080, `benches/decode.rs`'s
/// `SIZES`) is a pure downscale of the embedded 2200x1100 source - never an
/// upscale - by construction (see `ATTRIBUTION.md`).
pub fn real_photo_sized(width: u32, height: u32, format: ImageFormat) -> Vec<u8> {
    let ext = match format {
        ImageFormat::Jpeg => "jpg",
        ImageFormat::Png => "png",
        ImageFormat::WebP => "webp",
        _ => "bin",
    };
    cached(&format!("real_photo_{width}x{height}.{ext}"), || {
        let base = real_photo_base(REAL_PHOTO_PRIMARY_BYTES);
        let img = DynamicImage::ImageRgb8(cover_resize(&base, width, height));
        encode(&img, format)
    })
}

/// AVIF counterpart to `real_photo_sized`, mirroring
/// `photo_like_sized_avif`'s caller-supplied-encoder pattern (see that
/// function's own doc comment for why).
pub fn real_photo_sized_avif(
    width: u32,
    height: u32,
    encode_fn: impl FnOnce(&DynamicImage) -> Vec<u8>,
) -> Vec<u8> {
    cached(&format!("real_photo_{width}x{height}.avif"), || {
        let base = real_photo_base(REAL_PHOTO_PRIMARY_BYTES);
        let img = DynamicImage::ImageRgb8(cover_resize(&base, width, height));
        encode_fn(&img)
    })
}

/// Real-photo content from the *secondary* source (`earthrise.jpg`) -
/// structurally different from `blue-marble.jpg` (near-black space +
/// high-texture lunar regolith + a small high-detail Earth, vs. Blue
/// Marble's broad cloud/ocean/land texture), at an arbitrary size/format.
/// Used by `benches/pipeline.rs` so the real-vs-synthetic comparison isn't
/// resting on a single photo's particular compressibility. Native
/// resolution 1280x1280, so this is only called at sizes at or below that.
pub fn real_photo_secondary_sized(width: u32, height: u32, format: ImageFormat) -> Vec<u8> {
    let ext = match format {
        ImageFormat::Jpeg => "jpg",
        ImageFormat::Png => "png",
        ImageFormat::WebP => "webp",
        _ => "bin",
    };
    cached(&format!("real_photo_secondary_{width}x{height}.{ext}"), || {
        let base = real_photo_base(REAL_PHOTO_SECONDARY_BYTES);
        let img = DynamicImage::ImageRgb8(cover_resize(&base, width, height));
        encode(&img, format)
    })
}

pub const ORIENTED_W: u32 = 120;
pub const ORIENTED_H: u32 = 80;
/// Marker block side length, in canonical (already-upright) pixels - well
/// inside both the marker and background regions, so sampling a few pixels
/// in from any edge lands solidly in one colour even after JPEG's lossy
/// compression and any resize filtering a test applies on top.
const ORIENTED_MARKER: u32 = 20;

/// Canonical (already-upright) marker image used to build the EXIF-
/// orientation fixtures below (#33): a deliberately non-square `W`x`H`
/// image (so a 90/270-degree rotation bug shows up as a dimension swap, not
/// just a same-shape pixel mismatch) with a solid red marker block in its
/// top-left corner and solid blue everywhere else - "upright" here means
/// exactly this layout.
pub fn oriented_canonical() -> RgbImage {
    ImageBuffer::from_fn(ORIENTED_W, ORIENTED_H, |x, y| {
        if x < ORIENTED_MARKER && y < ORIENTED_MARKER {
            Rgb([220, 30, 30]) // marker: red
        } else {
            Rgb([30, 30, 220]) // background: blue
        }
    })
}

/// Builds a minimal, valid Exif TIFF blob - the `APP1` payload *minus* the
/// leading `"Exif\0\0"` marker, which `JpegEncoder::set_exif_metadata`
/// prepends itself (image-0.25.10 `src/codecs/jpeg/encoder.rs::write_exif`)
/// and the decode-side `zune-jpeg` strips back off before handing the
/// remainder to `Orientation::from_exif_chunk` (`zune-jpeg-0.5.15`
/// `src/headers.rs::parse_app1`) - containing exactly one IFD0 entry: the
/// Orientation tag (`0x0112`, TIFF type 3/SHORT, count 1) set to
/// `exif_orientation` (the standard 1-8 EXIF orientation code). Byte layout
/// mirrors exactly what `Orientation::from_exif_chunk`'s
/// `locate_orientation_entry` helper (image-0.25.10 `src/metadata.rs`)
/// parses: little-endian TIFF header, one directory entry, no next-IFD.
fn minimal_exif_orientation(exif_orientation: u8) -> Vec<u8> {
    let mut buf = Vec::with_capacity(26);
    buf.extend_from_slice(b"II"); // little-endian byte order
    buf.extend_from_slice(&42u16.to_le_bytes()); // TIFF magic
    buf.extend_from_slice(&8u32.to_le_bytes()); // IFD0 offset (right after this 8-byte header)
    buf.extend_from_slice(&1u16.to_le_bytes()); // 1 directory entry
    buf.extend_from_slice(&0x0112u16.to_le_bytes()); // tag: Orientation
    buf.extend_from_slice(&3u16.to_le_bytes()); // type: SHORT
    buf.extend_from_slice(&1u32.to_le_bytes()); // count: 1
    buf.extend_from_slice(&u16::from(exif_orientation).to_le_bytes()); // value (low 2 bytes of the 4-byte value field)
    buf.extend_from_slice(&0u16.to_le_bytes()); // padding (high 2 bytes of the value field)
    buf.extend_from_slice(&0u32.to_le_bytes()); // next IFD offset: none
    buf
}

/// A JPEG fixture whose *stored* pixel data is the algebraic inverse of
/// [`oriented_canonical`]'s transform for EXIF orientation `exif_orientation`
/// (1-8), tagged with that orientation in its Exif `Orientation` field -
/// exactly how a real camera's sensor output plus its orientation sensor
/// reading works: the pixels are stored however the sensor happened to be
/// held, and the tag says how to correct them for display.
///
/// Correctly decoding + autorotating this fixture must reproduce
/// `oriented_canonical()` exactly, dimensions included (orientations 5-8
/// swap width and height). The inverse per code is derived directly from
/// `DynamicImage::apply_orientation`'s own match arms (image-0.25.10
/// `src/images/dynimage.rs:1161-1179`):
///
/// | code | `apply_orientation` forward transform | inverse used to build `stored` |
/// |------|----------------------------------------|-------------------------------|
/// | 1    | identity                                | identity                      |
/// | 2    | `fliph`                                 | `fliph` (self-inverse)        |
/// | 3    | `rotate180`                             | `rotate180` (self-inverse)    |
/// | 4    | `flipv`                                 | `flipv` (self-inverse)        |
/// | 5    | `fliph(rotate90(x))`                    | `rotate270(fliph(x))`         |
/// | 6    | `rotate90(x)`                           | `rotate270(x)`                |
/// | 7    | `fliph(rotate270(x))`                   | `rotate90(fliph(x))`          |
/// | 8    | `rotate270(x)`                          | `rotate90(x)`                 |
///
/// so this is a from-first-principles inverse of the exact production
/// transform, not a round-trip through it.
pub fn oriented(exif_orientation: u8) -> Vec<u8> {
    cached(&format!("oriented_{exif_orientation}.jpg"), || {
        let canonical = DynamicImage::ImageRgb8(oriented_canonical());
        let stored = match exif_orientation {
            1 => canonical,
            2 => canonical.fliph(),
            3 => canonical.rotate180(),
            4 => canonical.flipv(),
            5 => canonical.fliph().rotate270(),
            6 => canonical.rotate270(),
            7 => canonical.fliph().rotate90(),
            8 => canonical.rotate90(),
            other => panic!("unsupported EXIF orientation value {other} (expected 1-8)"),
        };

        use image::ImageEncoder;

        let mut buf = Cursor::new(Vec::new());
        let mut encoder = image::codecs::jpeg::JpegEncoder::new(&mut buf);
        encoder
            .set_exif_metadata(minimal_exif_orientation(exif_orientation))
            .expect("JpegEncoder supports Exif metadata");
        stored
            .write_with_encoder(encoder)
            .expect("fixture encoding should never fail");
        buf.into_inner()
    })
}

/// Builds a raw, prefix-less TIFF-formatted Exif blob (same convention as
/// [`minimal_exif_orientation`] above) carrying **both** an `Orientation`
/// tag (0x0112) and a full GPS IFD (`GPSInfo`/0x8825 pointing at
/// `GPSLatitudeRef`/`GPSLatitude`/`GPSLongitudeRef`/`GPSLongitude`) - #5's
/// "keep metadata" tests need a real, privacy-sensitive field (GPS
/// coordinates), not just the bare Orientation tag `minimal_exif_orientation`
/// already covers, to prove strip-vs-keep actually differs in substance and
/// not merely in whether an (otherwise empty) APP1 segment is present at
/// all.
///
/// Byte layout (little-endian TIFF, `"II"`), sized and offset by hand so
/// every IFD's `next-IFD`/tag-value offset points at the byte right where
/// the following section actually starts - each `assert_eq!` below is a
/// self-check that a later edit to one section can't silently desync the
/// hardcoded offset baked into an earlier one:
/// - `0..8`    TIFF header (byte order, magic 42, IFD0 offset = 8)
/// - `8..38`   IFD0 - 2 entries (`Orientation`, `GPSInfo` pointer -> 38) + next-IFD (0)
/// - `38..92`  GPS IFD - 4 entries (`GPSLatitudeRef`, `GPSLatitude` -> 92,
///   `GPSLongitudeRef`, `GPSLongitude` -> 116) + next-IFD (0)
/// - `92..116` `GPSLatitude`'s 3 RATIONALs (degrees/minutes/seconds, denominator 1)
/// - `116..140` `GPSLongitude`'s 3 RATIONALs
///
/// The coordinates encoded (37 49 32 N, 122 28 42 W) are the Golden Gate
/// Bridge, San Francisco - a real, recognisable location, not placeholder
/// zeros, so a test asserting "GPS is gone" can't accidentally pass against
/// a degenerate all-zero value that might mean "unset" under some other
/// convention.
fn exif_orientation_and_gps(exif_orientation: u8) -> Vec<u8> {
    let mut buf = Vec::with_capacity(140);

    // --- TIFF header (0..8) ---
    buf.extend_from_slice(b"II");
    buf.extend_from_slice(&42u16.to_le_bytes());
    buf.extend_from_slice(&8u32.to_le_bytes()); // IFD0 offset

    // --- IFD0 (8..38): Orientation + GPSInfo pointer ---
    buf.extend_from_slice(&2u16.to_le_bytes()); // 2 entries
    // Orientation (0x0112, SHORT, count 1)
    buf.extend_from_slice(&0x0112u16.to_le_bytes());
    buf.extend_from_slice(&3u16.to_le_bytes());
    buf.extend_from_slice(&1u32.to_le_bytes());
    buf.extend_from_slice(&u16::from(exif_orientation).to_le_bytes());
    buf.extend_from_slice(&0u16.to_le_bytes()); // padding (high 2 bytes of value field)
    // GPSInfo (0x8825, LONG, count 1) -> GPS IFD at offset 38
    buf.extend_from_slice(&0x8825u16.to_le_bytes());
    buf.extend_from_slice(&4u16.to_le_bytes());
    buf.extend_from_slice(&1u32.to_le_bytes());
    buf.extend_from_slice(&38u32.to_le_bytes());
    buf.extend_from_slice(&0u32.to_le_bytes()); // next IFD: none
    assert_eq!(buf.len(), 38, "IFD0 must end exactly at the GPS IFD's offset");

    // --- GPS IFD (38..92): LatRef, Lat, LonRef, Lon ---
    buf.extend_from_slice(&4u16.to_le_bytes()); // 4 entries
    // GPSLatitudeRef (1, ASCII, count 2 incl. NUL) - "N\0" fits inline
    buf.extend_from_slice(&1u16.to_le_bytes());
    buf.extend_from_slice(&2u16.to_le_bytes());
    buf.extend_from_slice(&2u32.to_le_bytes());
    buf.extend_from_slice(b"N\0\0\0");
    // GPSLatitude (2, RATIONAL, count 3) -> data at offset 92
    buf.extend_from_slice(&2u16.to_le_bytes());
    buf.extend_from_slice(&5u16.to_le_bytes());
    buf.extend_from_slice(&3u32.to_le_bytes());
    buf.extend_from_slice(&92u32.to_le_bytes());
    // GPSLongitudeRef (3, ASCII, count 2 incl. NUL) - "W\0"
    buf.extend_from_slice(&3u16.to_le_bytes());
    buf.extend_from_slice(&2u16.to_le_bytes());
    buf.extend_from_slice(&2u32.to_le_bytes());
    buf.extend_from_slice(b"W\0\0\0");
    // GPSLongitude (4, RATIONAL, count 3) -> data at offset 116
    buf.extend_from_slice(&4u16.to_le_bytes());
    buf.extend_from_slice(&5u16.to_le_bytes());
    buf.extend_from_slice(&3u32.to_le_bytes());
    buf.extend_from_slice(&116u32.to_le_bytes());
    buf.extend_from_slice(&0u32.to_le_bytes()); // next IFD: none
    assert_eq!(buf.len(), 92, "GPS IFD must end exactly at the GPSLatitude data offset");

    // --- GPSLatitude data (92..116): 37 deg, 49 min, 32 sec ---
    for value in [37u32, 49, 32] {
        buf.extend_from_slice(&value.to_le_bytes());
        buf.extend_from_slice(&1u32.to_le_bytes()); // denominator
    }
    assert_eq!(
        buf.len(),
        116,
        "GPSLongitude data must start right after GPSLatitude's"
    );

    // --- GPSLongitude data (116..140): 122 deg, 28 min, 42 sec ---
    for value in [122u32, 28, 42] {
        buf.extend_from_slice(&value.to_le_bytes());
        buf.extend_from_slice(&1u32.to_le_bytes());
    }
    assert_eq!(buf.len(), 140);

    buf
}

/// A JPEG fixture (`oriented_canonical`'s pixels, undistorted - GPS/orientation
/// stripping is what's under test here, not the orientation-transform math
/// `oriented()` above already covers) whose Exif blob carries both a real
/// GPS location and the given `exif_orientation` code (#5). Used to prove:
/// - `sm`'s default (strip) drops the GPS coordinates from the output.
/// - `sm:0` (keep) forwards them, for every format that can carry Exif.
/// - When `exif_orientation != 1` and autorotate is on, the *kept* output's
///   own Orientation tag reads back as `1` (normalised), not the original
///   value - i.e. the double-rotation guard actually ran.
pub fn jpeg_with_gps_exif(exif_orientation: u8) -> Vec<u8> {
    cached(&format!("gps_exif_{exif_orientation}.jpg"), || {
        let canonical = DynamicImage::ImageRgb8(oriented_canonical());

        use image::ImageEncoder;

        let mut buf = Cursor::new(Vec::new());
        let mut encoder = image::codecs::jpeg::JpegEncoder::new(&mut buf);
        encoder
            .set_exif_metadata(exif_orientation_and_gps(exif_orientation))
            .expect("JpegEncoder supports Exif metadata");
        canonical
            .write_with_encoder(encoder)
            .expect("fixture encoding should never fail");
        buf.into_inner()
    })
}

/// Realistic EXIF payload size for phone/camera JPEGs (#88) - large enough
/// that the extraction cost the #88 bug was about actually shows up in a
/// benchmark, unlike every fixture above (all EXIF-free, verified: none of
/// `photo_like`/`flat`/`alpha`/`tiny`/`bomb`/`gravity_marker`/
/// `photo_like_sized` ever calls `set_exif_metadata`) and unlike
/// `exif_orientation_and_gps`'s ~140-byte blob (enough to prove correctness,
/// nowhere near enough to show up against decode/resize/encode time in a
/// benchmark). Comfortably under the 65531-byte hard limit a single JPEG
/// APP1 segment can carry (`JpegEncoder::write_segment`'s `u16` length
/// field, `image-0.25.10/src/codecs/jpeg/encoder.rs:284-288` - `data.len()
/// as u16 + 2` silently wraps past `u16::MAX` with no size check ahead of
/// it) - the same ceiling real camera/phone EXIF is bounded by, since it
/// also has to fit in one APP1 marker.
pub const REALISTIC_EXIF_SIZE: usize = 45 * 1024;

/// Extends [`exif_orientation_and_gps`] with a trailing "thumbnail" blob -
/// real embedded EXIF carries a small JPEG's compressed bytes in exactly
/// this position (referenced by an `IFD1`/`JPEGInterchangeFormat` pointer
/// this fixture doesn't bother wiring up, since nothing under test here
/// ever tries to *decode* the thumbnail, only to pay the cost of copying it
/// off the source) - padded with deterministic filler to
/// `REALISTIC_EXIF_SIZE` total, matching the tens-of-KB EXIF+thumbnail
/// blobs real camera/phone JPEGs carry.
///
/// Safe to just append: `zune_jpeg::headers::parse_app1` (the decode-side
/// reader) copies the *entire* APP1 payload verbatim into `exif_data`
/// (`zune-jpeg-0.5.15/src/headers.rs:553-555`) rather than parsing it
/// structurally, and `exif_orientation_and_gps`'s own IFD0/GPS-IFD
/// "next-IFD offset: none" terminators mean nothing tries to walk past this
/// trailing data as more IFD structure - from the decoder's point of view
/// it's inert padding, exactly like an unreferenced `IFD1` would be.
fn exif_orientation_gps_and_thumbnail(exif_orientation: u8) -> Vec<u8> {
    let mut buf = exif_orientation_and_gps(exif_orientation);

    // A genuine small JPEG - the same shape of bytes a real embedded
    // thumbnail is, not synthetic filler pretending to be one.
    let thumb = encode(
        &DynamicImage::ImageRgb8(gradient_noise_rgb(160, 120)),
        ImageFormat::Jpeg,
    );
    buf.extend_from_slice(&thumb);

    // Pad deterministically (seeded, not zeros - so this can't accidentally
    // compress away to nothing if anything downstream ever re-encodes it)
    // up to the realistic total size.
    let mut rng = rng_for("exif_thumbnail_padding");
    while buf.len() < REALISTIC_EXIF_SIZE {
        buf.push(rng.r#gen());
    }
    buf.truncate(REALISTIC_EXIF_SIZE);
    buf
}

/// 1920x1080 photo-like JPEG carrying a realistic (~45KB) EXIF blob - GPS +
/// orientation + an embedded thumbnail-shaped payload (#88). Every other
/// JPEG fixture in this file is EXIF-free by construction, which is exactly
/// how the #88 bug (EXIF extracted unconditionally in
/// `ImageService::decode_with_limits`, even on the default `strip_metadata`
/// path that immediately discards it in `encode_single_image`) went
/// unmeasured: nothing in this corpus paid the cost extracting a
/// real-world-sized blob would incur. This fixture exists so
/// `benches/pipeline.rs` can see that cost, strip vs keep.
pub fn photo_like_with_exif() -> Vec<u8> {
    cached("photo_like_with_exif.jpg", || {
        let img = DynamicImage::ImageRgb8(gradient_noise_rgb(PHOTO_LIKE_W, PHOTO_LIKE_H));

        use image::ImageEncoder;
        let mut out = Cursor::new(Vec::new());
        let mut encoder = image::codecs::jpeg::JpegEncoder::new(&mut out);
        encoder
            .set_exif_metadata(exif_orientation_gps_and_thumbnail(1))
            .expect("JpegEncoder supports Exif metadata");
        img.write_with_encoder(encoder)
            .expect("fixture encoding should never fail");
        out.into_inner()
    })
}

/// content-type for a fixture identified by name, as served by the
/// `benchmark` bin's local origin server and used to pick a decode/encode
/// extension in tests.
pub fn content_type_for(name: &str) -> &'static str {
    match name {
        "photo_like" | "tiny" => "image/jpeg",
        "flat" | "alpha" | "bomb" | "gravity_marker" => "image/png",
        _ => "application/octet-stream",
    }
}

/// Look up one of the named fixtures by string name (used by the local
/// fixture HTTP server in `src/bin/benchmark.rs`, where the set to serve is
/// configured via an env var).
pub fn by_name(name: &str) -> Option<Vec<u8>> {
    match name {
        "photo_like" => Some(photo_like()),
        "flat" => Some(flat()),
        "alpha" => Some(alpha()),
        "tiny" => Some(tiny()),
        "bomb" => Some(bomb()),
        "gravity_marker" => Some(gravity_marker()),
        _ => None,
    }
}
