name: Deploy Docs and Helm Chart

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      chart_changed: ${{ steps.changed_files.outputs.chart_yaml_changed }}
      docs_changed: ${{ steps.changed_files.outputs.docs_dir_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to diff against previous commits accurately

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v46
        with:
          base_sha: ${{ github.event.before }}
          sha: ${{ github.sha }}
          files_yaml: |
            chart_yaml:
              - helm/**
            docs_dir:
              - docs/**

  deploy:
    needs: determine_changes
    if: ${{ needs.determine_changes.outputs.chart_changed == 'true' && needs.determine_changes.outputs.docs_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # MkDocs Steps
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-minify-plugin
          pip install pymdown-extensions --force

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy MkDocs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # keep_files: false (default) is appropriate here.
          # The chart-releaser action will run after this and add its files
          # to the gh-pages branch without removing existing MkDocs files.

      # Helm Chart Steps
      - name: Configure Git
        # This step is generally good practice before actions that commit,
        # though chart-releaser-action might handle its own git config.
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        # No explicit GITHUB_TOKEN env var needed here for azure/setup-helm.

      - name: Add Helm repositories
        # This step was in the original 'deploy-helm-chart.yml'.
        # Include this if your charts in the 'helm/' directory have dependencies
        # on charts from 'bjw-s' that need to be resolved during packaging.
        # If your charts are self-contained or manage dependencies differently,
        # this step might be adjusted or removed.
        run: |
          helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: helm # Specifies the directory containing your Helm charts.
          # The chart-releaser-action handles checking out the gh-pages branch,
          # packaging charts, updating the index.yaml, committing, and pushing.
          # It is designed to be additive to the gh-pages branch.